# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return the minimum of two numbers.
#' 
#' @param a Numeric.
#' @param b Numeric.
#' @return The smaller of a or b.
NULL

#' Return the maximum of two numbers.
#' 
#' @param a Numeric.
#' @param b Numeric.
#' @return The larger of a or b.
NULL

#' Test for equality between numbers with 80 bit extended precision.
#' 
#' @param a Numeric.
#' @param b Numeric.
#' @param tol Numeric.
#' @return Integer 0 or 1.
NULL

#' Starting with the tail probability of finding some particular number of
#' successes less than k, update it to the tail probability of finding k or
#' more successes.
#' 
#' This is function is only useful in the context of this package, where we
#' have split the probability computation across several functions.
#' 
#' @param p Probability of exactly k successes.
#' @param k Number of successes after n draws.
#' @param N Size of the population.
#' @param K Number of successes in the population.
#' @param n Number of draws, without replacement.
#' @return Numeric between 0 and 1.
NULL

#' Compute the minimum hypergeometric score (mHG). It indicates the
#' probability of the observed density of ones at the beginning of the vector
#' under the assumption that all possible permutations of the list are equally
#' probable.
#' 
#' The optimal size of the beginning is discovered by iteratively increasing
#' the size and chooseing the one with the minimum hypergeometric score.
#' 
#' @param v Binary vector of ones and zeros.
#' @param N Size of the population.
#' @param K Number of successes in the population.
#' @param L Only consider scores for the first L observations.
#' @param X Require at least X ones to get a score less than 1.
#' @param scores A vector of mHG scores.
#' @param tol The tolerance for testing equality of two numbers.
NULL

#' Compute an XL-mHG p-value.
NULL

do_mHG_test <- function(v, N, K, L, X, mat, use_upper_bound = FALSE, verbose = FALSE, tolerance = 0.0000000000000001) {
    .Call('mhg_do_mHG_test', PACKAGE = 'mhg', v, N, K, L, X, mat, use_upper_bound, verbose, tolerance)
}

